#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt APPEND_HISTORY        # Write to the history when the shell exits, not inmediatelly.
unsetopt SHARE_HISTORY

# ROS environment setup

# Configuring rosmake to use up to 4 cores, while CPU load is available.
export ROS_PARALLEL_JOBS='-j4 -l4'

# This is needed for zsh to work with inner setup.sh,
# ATENTION: unset after sourceing setup.zsh
setopt clobber

# Setup for ROS Diamondback distro
#source /opt/ros/diamondback/setup.zsh

# Setup of development environment previous to upgrade to Ubuntu 12.04 precise
#source /home/daniel/Proyectos/ROS/setup.zsh

# Setup for ROS Fuerte distro
#source /opt/ros/fuerte/setup.zsh

# Setup of development environment overlay for ROS Fuerte
#source /home/daniel/Proyectos/ROS/fuerte_workspace/setup.zsh

# Setup of development environment overlay for Hector packages in ROS Fuerte
#source /home/daniel/Proyectos/ROS/hector_fuerte_workspace/setup.zsh

# Setup of development environment overlay for move_base_3D over ROS Fuerte
#source /home/daniel/Proyectos/ROS/fuerte_move_base_3D_workspace/setup.zsh

# Setup of development environment overlay for move_base_3D over ROS Fuerte (with all of its dependencies migrated to Fuerte version)
#source /home/daniel/Proyectos/ROS/fuerte_move_base_3D_migration/setup.zsh

# Setup of development environment overlay for amclgps over ROS Fuerte
#source ~/Proyectos/ROS/fuerte_amclgps_migration/setup.zsh

# Setup of development environment overlay for predictive_explorer over ROS Fuerte
#source /home/daniel/Proyectos/ROS/predictive_explorer_fuerte/setup.zsh

# Setup of development environment overlay for predictive_explorer_unified over ROS Fuerte
#source /home/daniel/Proyectos/ROS/predictive_explorer_workspace/setup.zsh

# Setup of development environment overlay for predictive_explorer_unified over ROS Fuerte
#source /home/daniel/Proyectos/ROS/predictive_explorer_fuerte_unified/setup.zsh

# Setup of development environment overlay for predictive_explorer_unified over ROS Fuerte in SSD
#source /media/9bb4b285-b2c9-488c-950c-6a96fda46180/home/daniel/Proyectos/ROS/predictive_explorer_fuerte_unified/setup.zsh

# Setup for ROS Hydro distro
# source /opt/ros/hydro/setup.zsh

# Setup of development environment overlay for hydro_simulators_workspace over ROS Hydro and Verdino Hydro workspace
#source /home/daniel/Proyectos/ROS/hydro_workspace/devel/setup.zsh

# Setup of development environment overlay for hydro_simulators_workspace over ROS Hydro and Verdino Hydro workspace
#source /home/daniel/Proyectos/ROS/hydro_simulators_workspace/devel/setup.bash

# Base Indigo Igloo
#source /opt/ros/indigo/setup.zsh

# Setup of development environment overlay for predictive_explorer over ROS Indigo (Catkin)
#source /home/daniel/Proyectos/ROS/predictive_explorer_indigo_workspace/devel/setup.zsh
 
# Setup of development environment overlay for predictive_explorer over ROS Indigo (Rosbuild)
#source /home/daniel/Proyectos/ROS/predictive_explorer_rosbuild_indigo_workspace/setup.zsh

# Setup of development environment overlay for LSD-SLAM over ROS Fuerte (Rosbuild)
#source /home/daniel/Proyectos/ROS/lsd_slam_fuerte/setup.zsh

# Setup of development environment overlay for IAI Kinect2 over ROS Hydro (Catkin)
# /home/daniel/Proyectos/ROS/iai_kinect2_hydro/devel/setup.zsh

# Setup of development environment overlay for Point Grey camera driver over ROS Hydro (Catkin)
#source /home/daniel/Proyectos/ROS/pointgrey_camera_driver_hydro/devel/setup.zsh

# Setup of development environment overlay for ETHZASL_ICP_MAPPING over ROS Indigo (Rosbuild)
#source /home/daniel/Proyectos/ROS/ethzasl_icp_mapping/devel/setup.zsh

# ATENTION Reseting after sourcing setup.zsh
unsetopt clobber
 
export EDITOR='subl'
 
# Gazebo environment variables
 
export GAZEBO_MODEL_PATH=~/Proyectos/ROS/hydro_simulators_workspace/src/grull_verdino_simulator_gazebo/models
 
# V-REP ROS communication
#export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/Descargas/V-REP_PRO_EDU_V3_1_1_64_Linux/programming/ros_stacks/vrep
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/Descargas/V-REP_PRO_EDU_V3_1_2_64_Linux/programming/ros_stacks-rosBuild/vrep
 
# vrep_ros_bridge setup
export VREP_ROOT_DIR=/home/daniel/Descargas/V-REP_PRO_EDU_V3_1_1_64_Linux/
 
# linuxtrack (TrackIR, WiiMote, etc. library and drivers)
export PATH=${PATH}:/opt/linuxtrack/bin

# Latex enviroment variables
#PATH=/usr/local/texlive/2012/bin/x86_64-linux:$PATH

# SmartGitHG Java JRE path
export SMARTGITHG_JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre"
